# Generated by Django 5.0.4 on 2024-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongmodel',
            name='senha',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='ongmodel',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descriacao'),
        ),
        migrations.AlterField(
            model_name='ongmodel',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ongmodel',
            name='nome',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ongmodel',
            name='telefone',
            field=models.CharField(default='', max_length=15, verbose_name='Telefone'),
        ),
    ]
