# Generated by Django 5.0.4 on 2024-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ongmodel_senha_alter_ongmodel_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongmodel',
            old_name='descricao',
            new_name='Descricao',
        ),
        migrations.RenameField(
            model_name='ongmodel',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='ongmodel',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='ongmodel',
            old_name='telefone',
            new_name='Telefone',
        ),
        migrations.RemoveField(
            model_name='ongmodel',
            name='senha',
        ),
        migrations.AddField(
            model_name='ongmodel',
            name='Senha',
            field=models.CharField(default='', max_length=128, verbose_name='Senha'),
        ),
    ]
