# Generated by Django 5.0.4 on 2024-06-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ongmodel_id_ongmodel_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongmodel',
            name='Descricao',
        ),
    ]
