# Generated by Django 5.0.4 on 2024-06-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ongmodel_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ONGModel',
        ),
    ]
