# Generated by Django 5.0.4 on 2024-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_descricao_ongmodel_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='ongmodel',
            name='CNPJ',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='CNPJ'),
        ),
    ]
